---
title: "Reduce_file_size"
author: "Jonelle"
date: "11/23/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library("imager")
```

```{r}
original = imager::load.image("slides/Martens_lab_2021.png")

```

```{r}
d = dim(original) [1:2]
d
```

```{r}
fs::file_info("slides/Martens_lab_2021.png") $size
```

```{r}
scale = max(d / 500)
img = imager::resize(original,
                     imager::width(original) / scale,
                     imager::height(original) / scale,
                     interpolation_type = 6)
img
```


```{r}
#square_img = imager::pad(img, 
                         nPix = 500 - height(img), 
                         axes = "y", 
                         val = "white")
#imager::save.image(square_img, file = "slides/1947superJumbo2.png")

```


```{r}
#imager::save.image(square_img, file = "slides/1947superJumbo2.png")
#square_img
```

```{r}
imager::save.image(img, file = "slides/Martens_lab_2021sm.png")
img
```

```{r}
fs::file_info("slides/Martens_lab_2021sm.png")$size
```

